# Generated by Django 3.0.5 on 2020-06-13 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название товара')),
                ('description', models.TextField(verbose_name='описание товара')),
                ('price', models.FloatField(verbose_name='цена товара')),
                ('image', models.CharField(default='untitled', max_length=50, verbose_name='индетификатор файла изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст комента')),
                ('added', models.DateField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('mark', models.IntegerField(verbose_name='оценка')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
