# Generated by Django 3.0.5 on 2020-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(height_field=200, null=True, upload_to='../images', width_field=200),
        ),
    ]
