# Generated by Django 3.0.5 on 2020-06-17 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0004_remove_item_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='контакт для связи')),
                ('added', models.DateField(default=django.utils.timezone.now, verbose_name='дата добавления')),
                ('is_done', models.BooleanField(default=False, verbose_name='заказ обработан')),
            ],
        ),
        migrations.CreateModel(
            name='OrderElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Кол-ва товара')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShopApp.Order')),
            ],
        ),
    ]
