# Generated by Django 3.0.5 on 2020-06-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0005_order_orderelement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number',
            new_name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Jhon', max_length=50, verbose_name='имя заказчика'),
            preserve_default=False,
        ),
    ]
